allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.12.0'
  - '@astrojs/markdown-satteri@0.4.3'
  - astro@7.3.6
  - miniflare@5.20261006.1-alpha
  - wrangler@4.149.0
